/**
 * Core 250 single-word vocabulary for Colombian Spanish
 * Selected based on frequency, utility, and fluency principles
 * Focus: Most useful words to communicate about almost everything
 */

export interface CoreWord {
  spanish: string;
  english: string;
  category: 'essential' | 'verbs' | 'adjectives' | 'nouns' | 'expressions';
}

export const coreVocabulary: CoreWord[] = [
  // ESSENTIAL (50 words) - Can't communicate without these
  { spanish: 'sí', english: 'yes', category: 'essential' },
  { spanish: 'no', english: 'no', category: 'essential' },
  { spanish: 'hola', english: 'hello', category: 'essential' },
  { spanish: 'gracias', english: 'thanks', category: 'essential' },
  { spanish: 'por favor', english: 'please', category: 'essential' },
  { spanish: 'perdón', english: 'sorry', category: 'essential' },
  { spanish: 'adiós', english: 'goodbye', category: 'essential' },
  { spanish: 'yo', english: 'I', category: 'essential' },
  { spanish: 'tú', english: 'you', category: 'essential' },
  { spanish: 'él', english: 'he', category: 'essential' },
  { spanish: 'ella', english: 'she', category: 'essential' },
  { spanish: 'nosotros', english: 'we', category: 'essential' },
  { spanish: 'qué', english: 'what', category: 'essential' },
  { spanish: 'quién', english: 'who', category: 'essential' },
  { spanish: 'dónde', english: 'where', category: 'essential' },
  { spanish: 'cuándo', english: 'when', category: 'essential' },
  { spanish: 'cómo', english: 'how', category: 'essential' },
  { spanish: 'por qué', english: 'why', category: 'essential' },
  { spanish: 'cuánto', english: 'how much', category: 'essential' },
  { spanish: 'cuál', english: 'which', category: 'essential' },
  { spanish: 'y', english: 'and', category: 'essential' },
  { spanish: 'o', english: 'or', category: 'essential' },
  { spanish: 'pero', english: 'but', category: 'essential' },
  { spanish: 'porque', english: 'because', category: 'essential' },
  { spanish: 'si', english: 'if', category: 'essential' },
  { spanish: 'cuando', english: 'when', category: 'essential' },
  { spanish: 'este', english: 'this', category: 'essential' },
  { spanish: 'ese', english: 'that', category: 'essential' },
  { spanish: 'aquí', english: 'here', category: 'essential' },
  { spanish: 'allí', english: 'there', category: 'essential' },
  { spanish: 'ahora', english: 'now', category: 'essential' },
  { spanish: 'después', english: 'after', category: 'essential' },
  { spanish: 'antes', english: 'before', category: 'essential' },
  { spanish: 'hoy', english: 'today', category: 'essential' },
  { spanish: 'mañana', english: 'tomorrow', category: 'essential' },
  { spanish: 'ayer', english: 'yesterday', category: 'essential' },
  { spanish: 'bien', english: 'good/well', category: 'essential' },
  { spanish: 'mal', english: 'bad/badly', category: 'essential' },
  { spanish: 'más', english: 'more', category: 'essential' },
  { spanish: 'menos', english: 'less', category: 'essential' },
  { spanish: 'muy', english: 'very', category: 'essential' },
  { spanish: 'poco', english: 'little', category: 'essential' },
  { spanish: 'mucho', english: 'much/many', category: 'essential' },
  { spanish: 'todo', english: 'all/everything', category: 'essential' },
  { spanish: 'nada', english: 'nothing', category: 'essential' },
  { spanish: 'algo', english: 'something', category: 'essential' },
  { spanish: 'siempre', english: 'always', category: 'essential' },
  { spanish: 'nunca', english: 'never', category: 'essential' },
  { spanish: 'también', english: 'also', category: 'essential' },
  { spanish: 'tampoco', english: 'neither', category: 'essential' },

  // VERBS (80 words) - Core action words
  { spanish: 'ser', english: 'to be', category: 'verbs' },
  { spanish: 'estar', english: 'to be', category: 'verbs' },
  { spanish: 'tener', english: 'to have', category: 'verbs' },
  { spanish: 'hacer', english: 'to do/make', category: 'verbs' },
  { spanish: 'ir', english: 'to go', category: 'verbs' },
  { spanish: 'venir', english: 'to come', category: 'verbs' },
  { spanish: 'querer', english: 'to want', category: 'verbs' },
  { spanish: 'poder', english: 'can/to be able', category: 'verbs' },
  { spanish: 'deber', english: 'should/must', category: 'verbs' },
  { spanish: 'saber', english: 'to know', category: 'verbs' },
  { spanish: 'conocer', english: 'to know/meet', category: 'verbs' },
  { spanish: 'decir', english: 'to say/tell', category: 'verbs' },
  { spanish: 'hablar', english: 'to speak', category: 'verbs' },
  { spanish: 'ver', english: 'to see', category: 'verbs' },
  { spanish: 'mirar', english: 'to look/watch', category: 'verbs' },
  { spanish: 'escuchar', english: 'to listen', category: 'verbs' },
  { spanish: 'oír', english: 'to hear', category: 'verbs' },
  { spanish: 'dar', english: 'to give', category: 'verbs' },
  { spanish: 'poner', english: 'to put', category: 'verbs' },
  { spanish: 'traer', english: 'to bring', category: 'verbs' },
  { spanish: 'llevar', english: 'to take/carry', category: 'verbs' },
  { spanish: 'encontrar', english: 'to find', category: 'verbs' },
  { spanish: 'buscar', english: 'to look for', category: 'verbs' },
  { spanish: 'tomar', english: 'to take/drink', category: 'verbs' },
  { spanish: 'comer', english: 'to eat', category: 'verbs' },
  { spanish: 'beber', english: 'to drink', category: 'verbs' },
  { spanish: 'dormir', english: 'to sleep', category: 'verbs' },
  { spanish: 'despertar', english: 'to wake up', category: 'verbs' },
  { spanish: 'trabajar', english: 'to work', category: 'verbs' },
  { spanish: 'estudiar', english: 'to study', category: 'verbs' },
  { spanish: 'vivir', english: 'to live', category: 'verbs' },
  { spanish: 'pensar', english: 'to think', category: 'verbs' },
  { spanish: 'creer', english: 'to believe', category: 'verbs' },
  { spanish: 'sentir', english: 'to feel', category: 'verbs' },
  { spanish: 'amar', english: 'to love', category: 'verbs' },
  { spanish: 'gustar', english: 'to like', category: 'verbs' },
  { spanish: 'necesitar', english: 'to need', category: 'verbs' },
  { spanish: 'comprar', english: 'to buy', category: 'verbs' },
  { spanish: 'vender', english: 'to sell', category: 'verbs' },
  { spanish: 'pagar', english: 'to pay', category: 'verbs' },
  { spanish: 'costar', english: 'to cost', category: 'verbs' },
  { spanish: 'abrir', english: 'to open', category: 'verbs' },
  { spanish: 'cerrar', english: 'to close', category: 'verbs' },
  { spanish: 'empezar', english: 'to begin', category: 'verbs' },
  { spanish: 'terminar', english: 'to finish', category: 'verbs' },
  { spanish: 'seguir', english: 'to follow/continue', category: 'verbs' },
  { spanish: 'parar', english: 'to stop', category: 'verbs' },
  { spanish: 'esperar', english: 'to wait/hope', category: 'verbs' },
  { spanish: 'llegar', english: 'to arrive', category: 'verbs' },
  { spanish: 'salir', english: 'to leave/go out', category: 'verbs' },
  { spanish: 'entrar', english: 'to enter', category: 'verbs' },
  { spanish: 'volver', english: 'to return', category: 'verbs' },
  { spanish: 'regresar', english: 'to return', category: 'verbs' },
  { spanish: 'quedar', english: 'to remain/stay', category: 'verbs' },
  { spanish: 'subir', english: 'to go up', category: 'verbs' },
  { spanish: 'bajar', english: 'to go down', category: 'verbs' },
  { spanish: 'caminar', english: 'to walk', category: 'verbs' },
  { spanish: 'correr', english: 'to run', category: 'verbs' },
  { spanish: 'sentarse', english: 'to sit', category: 'verbs' },
  { spanish: 'levantarse', english: 'to get up', category: 'verbs' },
  { spanish: 'llamar', english: 'to call', category: 'verbs' },
  { spanish: 'preguntar', english: 'to ask', category: 'verbs' },
  { spanish: 'responder', english: 'to answer', category: 'verbs' },
  { spanish: 'ayudar', english: 'to help', category: 'verbs' },
  { spanish: 'enseñar', english: 'to teach/show', category: 'verbs' },
  { spanish: 'aprender', english: 'to learn', category: 'verbs' },
  { spanish: 'leer', english: 'to read', category: 'verbs' },
  { spanish: 'escribir', english: 'to write', category: 'verbs' },
  { spanish: 'entender', english: 'to understand', category: 'verbs' },
  { spanish: 'olvidar', english: 'to forget', category: 'verbs' },
  { spanish: 'recordar', english: 'to remember', category: 'verbs' },
  { spanish: 'perder', english: 'to lose', category: 'verbs' },
  { spanish: 'ganar', english: 'to win/earn', category: 'verbs' },
  { spanish: 'jugar', english: 'to play', category: 'verbs' },
  { spanish: 'bailar', english: 'to dance', category: 'verbs' },
  { spanish: 'cantar', english: 'to sing', category: 'verbs' },
  { spanish: 'reír', english: 'to laugh', category: 'verbs' },
  { spanish: 'llorar', english: 'to cry', category: 'verbs' },
  { spanish: 'cambiar', english: 'to change', category: 'verbs' },

  // ADJECTIVES (50 words) - Describing words
  { spanish: 'bueno', english: 'good', category: 'adjectives' },
  { spanish: 'malo', english: 'bad', category: 'adjectives' },
  { spanish: 'grande', english: 'big', category: 'adjectives' },
  { spanish: 'pequeño', english: 'small', category: 'adjectives' },
  { spanish: 'nuevo', english: 'new', category: 'adjectives' },
  { spanish: 'viejo', english: 'old', category: 'adjectives' },
  { spanish: 'joven', english: 'young', category: 'adjectives' },
  { spanish: 'feliz', english: 'happy', category: 'adjectives' },
  { spanish: 'triste', english: 'sad', category: 'adjectives' },
  { spanish: 'cansado', english: 'tired', category: 'adjectives' },
  { spanish: 'bonito', english: 'pretty', category: 'adjectives' },
  { spanish: 'feo', english: 'ugly', category: 'adjectives' },
  { spanish: 'fácil', english: 'easy', category: 'adjectives' },
  { spanish: 'difícil', english: 'difficult', category: 'adjectives' },
  { spanish: 'importante', english: 'important', category: 'adjectives' },
  { spanish: 'necesario', english: 'necessary', category: 'adjectives' },
  { spanish: 'rápido', english: 'fast', category: 'adjectives' },
  { spanish: 'lento', english: 'slow', category: 'adjectives' },
  { spanish: 'alto', english: 'tall/high', category: 'adjectives' },
  { spanish: 'bajo', english: 'short/low', category: 'adjectives' },
  { spanish: 'largo', english: 'long', category: 'adjectives' },
  { spanish: 'corto', english: 'short', category: 'adjectives' },
  { spanish: 'caliente', english: 'hot', category: 'adjectives' },
  { spanish: 'frío', english: 'cold', category: 'adjectives' },
  { spanish: 'rico', english: 'delicious/rich', category: 'adjectives' },
  { spanish: 'pobre', english: 'poor', category: 'adjectives' },
  { spanish: 'caro', english: 'expensive', category: 'adjectives' },
  { spanish: 'barato', english: 'cheap', category: 'adjectives' },
  { spanish: 'lleno', english: 'full', category: 'adjectives' },
  { spanish: 'vacío', english: 'empty', category: 'adjectives' },
  { spanish: 'abierto', english: 'open', category: 'adjectives' },
  { spanish: 'cerrado', english: 'closed', category: 'adjectives' },
  { spanish: 'listo', english: 'ready/smart', category: 'adjectives' },
  { spanish: 'ocupado', english: 'busy', category: 'adjectives' },
  { spanish: 'libre', english: 'free', category: 'adjectives' },
  { spanish: 'solo', english: 'alone/only', category: 'adjectives' },
  { spanish: 'juntos', english: 'together', category: 'adjectives' },
  { spanish: 'mismo', english: 'same', category: 'adjectives' },
  { spanish: 'diferente', english: 'different', category: 'adjectives' },
  { spanish: 'otro', english: 'other/another', category: 'adjectives' },
  { spanish: 'último', english: 'last', category: 'adjectives' },
  { spanish: 'primero', english: 'first', category: 'adjectives' },
  { spanish: 'mejor', english: 'better/best', category: 'adjectives' },
  { spanish: 'peor', english: 'worse/worst', category: 'adjectives' },
  { spanish: 'seguro', english: 'sure/safe', category: 'adjectives' },
  { spanish: 'peligroso', english: 'dangerous', category: 'adjectives' },
  { spanish: 'limpio', english: 'clean', category: 'adjectives' },
  { spanish: 'sucio', english: 'dirty', category: 'adjectives' },
  { spanish: 'interesante', english: 'interesting', category: 'adjectives' },
  { spanish: 'aburrido', english: 'boring', category: 'adjectives' },

  // NOUNS (50 words) - Essential things and people
  { spanish: 'persona', english: 'person', category: 'nouns' },
  { spanish: 'hombre', english: 'man', category: 'nouns' },
  { spanish: 'mujer', english: 'woman', category: 'nouns' },
  { spanish: 'niño', english: 'boy/child', category: 'nouns' },
  { spanish: 'niña', english: 'girl', category: 'nouns' },
  { spanish: 'amigo', english: 'friend', category: 'nouns' },
  { spanish: 'familia', english: 'family', category: 'nouns' },
  { spanish: 'casa', english: 'house', category: 'nouns' },
  { spanish: 'calle', english: 'street', category: 'nouns' },
  { spanish: 'ciudad', english: 'city', category: 'nouns' },
  { spanish: 'país', english: 'country', category: 'nouns' },
  { spanish: 'mundo', english: 'world', category: 'nouns' },
  { spanish: 'día', english: 'day', category: 'nouns' },
  { spanish: 'noche', english: 'night', category: 'nouns' },
  { spanish: 'mañana', english: 'morning', category: 'nouns' },
  { spanish: 'tarde', english: 'afternoon', category: 'nouns' },
  { spanish: 'hora', english: 'hour/time', category: 'nouns' },
  { spanish: 'tiempo', english: 'time/weather', category: 'nouns' },
  { spanish: 'año', english: 'year', category: 'nouns' },
  { spanish: 'mes', english: 'month', category: 'nouns' },
  { spanish: 'semana', english: 'week', category: 'nouns' },
  { spanish: 'comida', english: 'food', category: 'nouns' },
  { spanish: 'agua', english: 'water', category: 'nouns' },
  { spanish: 'dinero', english: 'money', category: 'nouns' },
  { spanish: 'trabajo', english: 'work', category: 'nouns' },
  { spanish: 'escuela', english: 'school', category: 'nouns' },
  { spanish: 'carro', english: 'car', category: 'nouns' },
  { spanish: 'bus', english: 'bus', category: 'nouns' },
  { spanish: 'taxi', english: 'taxi', category: 'nouns' },
  { spanish: 'baño', english: 'bathroom', category: 'nouns' },
  { spanish: 'cama', english: 'bed', category: 'nouns' },
  { spanish: 'mesa', english: 'table', category: 'nouns' },
  { spanish: 'silla', english: 'chair', category: 'nouns' },
  { spanish: 'puerta', english: 'door', category: 'nouns' },
  { spanish: 'ventana', english: 'window', category: 'nouns' },
  { spanish: 'teléfono', english: 'phone', category: 'nouns' },
  { spanish: 'computadora', english: 'computer', category: 'nouns' },
  { spanish: 'libro', english: 'book', category: 'nouns' },
  { spanish: 'mano', english: 'hand', category: 'nouns' },
  { spanish: 'cabeza', english: 'head', category: 'nouns' },
  { spanish: 'ojo', english: 'eye', category: 'nouns' },
  { spanish: 'boca', english: 'mouth', category: 'nouns' },
  { spanish: 'nombre', english: 'name', category: 'nouns' },
  { spanish: 'problema', english: 'problem', category: 'nouns' },
  { spanish: 'lugar', english: 'place', category: 'nouns' },
  { spanish: 'cosa', english: 'thing', category: 'nouns' },
  { spanish: 'vida', english: 'life', category: 'nouns' },
  { spanish: 'amor', english: 'love', category: 'nouns' },
  { spanish: 'pregunta', english: 'question', category: 'nouns' },
  { spanish: 'respuesta', english: 'answer', category: 'nouns' },

  // EXPRESSIONS (20 words) - Colombian/useful phrases
  { spanish: 'dale', english: 'okay/go ahead', category: 'expressions' },
  { spanish: 'listo', english: 'ready/done', category: 'expressions' },
  { spanish: 'claro', english: 'of course', category: 'expressions' },
  { spanish: 'tranquilo', english: 'calm/relax', category: 'expressions' },
  { spanish: 'chévere', english: 'cool/great', category: 'expressions' },
  { spanish: 'bacano', english: 'cool/awesome', category: 'expressions' },
  { spanish: 'parcero', english: 'buddy/friend', category: 'expressions' },
  { spanish: 'vaina', english: 'thing/stuff', category: 'expressions' },
  { spanish: 'chimba', english: 'awesome', category: 'expressions' },
  { spanish: 'berraco', english: 'tough/awesome', category: 'expressions' },
  { spanish: 'ahorita', english: 'right now', category: 'expressions' },
  { spanish: 'ya', english: 'already/now', category: 'expressions' },
  { spanish: 'todavía', english: 'still/yet', category: 'expressions' },
  { spanish: 'apenas', english: 'just/barely', category: 'expressions' },
  { spanish: 'entonces', english: 'then/so', category: 'expressions' },
  { spanish: 'mientras', english: 'while', category: 'expressions' },
  { spanish: 'aunque', english: 'although', category: 'expressions' },
  { spanish: 'además', english: 'besides', category: 'expressions' },
  { spanish: 'según', english: 'according to', category: 'expressions' },
  { spanish: 'quizás', english: 'maybe/perhaps', category: 'expressions' },
];
